version: 0.2

env:

	variables:
		$3_destination_bucket: codebuild-ap-south-1-srm-production-output-bucket
		repo_base: /root/.m2/repository/com/srm

phases:
	install:
		commands:
			- echo Nothing to do in the install phase...
	pre_build:
		commands:
			- echo Nothing to do in the pre_build phase...
	build:
		commands:
			- echo Build started on “date”
			- mvn install
	post_build:
		commands:
			- echo Uploading vivcommon-1.6.0. jar
			- aws s3 cp $repo_base/vivcommon/1.6.0/vivcommon-1.0.0.jar s3://$s3_destination_bucket/vivcommon/target/vivcommon-1.0.0.jar

artifacts:
	files:
	- target/vivcommon-1.0.0.jar

cache:
	paths:
			- ‘$repo_base.vivcormor /1.0.8/vivcormot-1.9.8.jar’